/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Servidor;

import Clases.Platillo;
import Clases.TipoPlatillo;
import Clases.imgHandler;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author retr0
 */
public class CreadorNoBebidas extends javax.swing.JFrame {

    public Platillo platillo;
    private File Archivo;
    public byte[] bytesIMG=null;
    private imgHandler gestion=new imgHandler();
    private javax.swing.JFileChooser selected = new javax.swing.JFileChooser();
    private ArrayList<String> platillos;
    public boolean platoValido=false;
    

    public Platillo getPlatillo() {
        return platillo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        txfDescripcion = new javax.swing.JTextField();
        txtTipoPorcion = new javax.swing.JTextField();
        txfCaloriasPorcion = new javax.swing.JTextField();
        txfPrecio = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnAnadirIMG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGramoporcion = new javax.swing.JTextField();
        txtkcalGrano = new javax.swing.JTextField();
        radioPoste = new javax.swing.JRadioButton();
        radioEntrada = new javax.swing.JRadioButton();
        radioPlatoF = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Tipo de porción:");

        jLabel5.setText("Calorías por porción:");

        jLabel7.setText("Precio:");

        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAnadirIMG.setText("Añadir Imagen");
        btnAnadirIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirIMGActionPerformed(evt);
            }
        });

        jLabel1.setText("Gramos por Porcion");

        jLabel6.setText("Kcal por gramo");

        txtkcalGrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkcalGranoActionPerformed(evt);
            }
        });

        radioPoste.setText("Postre");
        radioPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPosteActionPerformed(evt);
            }
        });

        radioEntrada.setText("Entrada");
        radioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntradaActionPerformed(evt);
            }
        });

        radioPlatoF.setText("Plato Fuerte");
        radioPlatoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPlatoFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnadirIMG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioEntrada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioPlatoF))
                                    .addComponent(txfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txfDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtTipoPorcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txfCaloriasPorcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txfPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtGramoporcion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkcalGrano, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioPoste)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipoPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfCaloriasPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGramoporcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkcalGrano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPoste)
                    .addComponent(radioEntrada)
                    .addComponent(radioPlatoF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnVolver)
                    .addComponent(btnAnadirIMG))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        boolean esNuevo=true;
        for(String s:platillos){
            if(txfNombre.getText().equals(s)){
                esNuevo=false;
                break;
            }
        }
        if(esNuevo){
            platillo= new Platillo();
            TipoPlatillo hh=null;
            if(radioEntrada.isSelected()){
                platillo.setCodClave("ETR"+platillo.getNombre());
                hh=TipoPlatillo.ETR;
            }else if(radioPlatoF.isSelected()){
                platillo.setCodClave("PRN"+platillo.getNombre());
                hh=TipoPlatillo.PRN;
            }else if(radioPoste.isSelected()){
                platillo.setCodClave("PTR"+platillo.getNombre());
                hh=TipoPlatillo.PTR;
            }else{
                esNuevo=false;
            }
            if(esNuevo){
                platillo= new Platillo(txfNombre.getText(), txfDescripcion.getText(), Double.parseDouble(txfPrecio.getText()),
                    txtTipoPorcion.getText(), "Bebida"+txfNombre.getText(), Integer.parseInt(txfCaloriasPorcion.getText()),
                    Double.valueOf(txtkcalGrano.getText()), Double.valueOf(txtGramoporcion.getText()), hh);
                if(bytesIMG!=null){
                   platillo.setImagen(bytesIMG); 
                }
                
                setVoid();
                platoValido=true;
                JOptionPane.showMessageDialog(this, "Plato Creado Correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione una categoria de plato");
            }
            
        }else{
           JOptionPane.showMessageDialog(this, "Plato Repetido, Intente de nuevo"); 
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    public void setVoid(){
        txfCaloriasPorcion.setText("");
        txfDescripcion.setText("");
        txfNombre.setText("");
        txfPrecio.setText("");
        txtTipoPorcion.setText("");
        txtGramoporcion.setText("");
        txtkcalGrano.setText("");
    }
    
    private void btnAnadirIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirIMGActionPerformed
        if(selected.showDialog(this, "Abrir Archivo")== JFileChooser.APPROVE_OPTION){
            Archivo= selected.getSelectedFile();
            if(Archivo.canRead()){
                if(Archivo.getName().endsWith(".jpg")||Archivo.getName().endsWith(".gif")||Archivo.getName().endsWith(".png")){
                    bytesIMG = gestion.AbrirIMG(Archivo);
                }else{
                    JOptionPane.showMessageDialog(null, "Selecione un archivo valido");
                }
            }
        }
    }//GEN-LAST:event_btnAnadirIMGActionPerformed

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void txtkcalGranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkcalGranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkcalGranoActionPerformed

    private void radioPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPosteActionPerformed
        radioEntrada.setSelected(false);
        radioPlatoF.setSelected(false);
        radioPoste.setSelected(true);
    }//GEN-LAST:event_radioPosteActionPerformed

    private void radioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntradaActionPerformed
        radioEntrada.setSelected(true);
        radioPlatoF.setSelected(false);
        radioPoste.setSelected(false);
    }//GEN-LAST:event_radioEntradaActionPerformed

    private void radioPlatoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPlatoFActionPerformed
        radioEntrada.setSelected(false);
        radioPlatoF.setSelected(true);
        radioPoste.setSelected(false);
    }//GEN-LAST:event_radioPlatoFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirIMG;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton radioEntrada;
    private javax.swing.JRadioButton radioPlatoF;
    private javax.swing.JRadioButton radioPoste;
    private javax.swing.JTextField txfCaloriasPorcion;
    private javax.swing.JTextField txfDescripcion;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPrecio;
    private javax.swing.JTextField txtGramoporcion;
    private javax.swing.JTextField txtTipoPorcion;
    private javax.swing.JTextField txtkcalGrano;
    // End of variables declaration//GEN-END:variables


    public CreadorNoBebidas(ArrayList<String> platillos) {//se le pasa los datos del platillo que va a modificar
        initComponents();
        this.platillos=platillos;
    }


}
